### ISSUE TITLE
IServiceCollection does not contain AddCosmosStore<>

### ISSUE THREAD

**Issue by kklan** [Elfocrash/Cosmonaut#10]
Hi,

I'm trying to set up Cosmonaut with my .NetASPCore project. I followed you video tutorial but I'm getting an error. How can I solve this issue?
Attached screenshot.
<img width="751" alt="screen shot 2018-05-19 at 2 18 31 pm" src="https://user-images.githubusercontent.com/18134352/40273147-dbfa4a7a-5b6f-11e8-9c28-b12d45c0cd4b.png">

**Comment by Elfocrash** [comment]
Hello @kklan.

Did you try adding `using Cosmonaut.Extensions;` ?

**Comment by kklan** [comment]
Thanks! That worked.
