### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'Cosmonaut.ICosmosStore`1[SocialNet.Models.User]' while attempting to activate 'SocialNet.Controllers.UserController'.

### ISSUE THREAD

**Issue by kklan** [Elfocrash/Cosmonaut#11]
Hi,

Got another error while following the video. Attached below:
<img width="1292" alt="screen shot 2018-05-19 at 4 19 27 pm" src="https://user-images.githubusercontent.com/18134352/40274008-0609512e-5b81-11e8-9290-d1456a38f4a3.png">

My controller class looks like this:

<img width="624" alt="screen shot 2018-05-19 at 4 22 30 pm" src="https://user-images.githubusercontent.com/18134352/40274011-14f07bae-5b81-11e8-97c5-6cc6651fe6ef.png">

Also is there any way you can provide me a download link of the example project you work with in your Getting started video?

Thanks
Kunal

**Comment by Elfocrash** [comment]
Are you sure you registered the correct `User` class? There might be some ambiguity issue with the name `User` as i don't see you using the `using Models;` on `Startup.cs`.

I would recommend renaming the `User` class to `AppUser` or something, just to test.

Also no the project is not uploaded anywhere but i can add it on Github if you need it.

**Comment by kklan** [comment]
Okay I will give this a try. Meanwhile, it would be a great help if you can add the project to Github.

Kunal

**Comment by Elfocrash** [comment]
Here you go https://github.com/Elfocrash/CosmosDBCRUDTutorial

**Comment by kklan** [comment]
Awesome, that was it. Thank you.

**Comment by Elfocrash** [comment]
You're welcome! 😄 Consider giving the project a star if you find it useful.
