### ISSUE TITLE
Query execution metrics

### ISSUE THREAD

**Issue by AKlaus** [Elfocrash/Cosmonaut#125]
Is it possible to access [query execution metrics](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-query-metrics#query-execution-metrics)?
It seems that both layers (Cosmonaut and EF Core 3) don't expose it. Am I right?

**Comment by Elfocrash** [comment]
Cosmonaut isn't exposing it in the code but everything is logged and you can create a custom event source to capture it
