### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by kklan** [Elfocrash/Cosmonaut#15]
So I was following what you suggested that I create another collection to save relationships.

This is how I set it up:
1. Model
<img width="420" alt="screen shot 2018-05-20 at 2 40 16 pm" src="https://user-images.githubusercontent.com/18134352/40283980-006cd2de-5c3c-11e8-8287-c29d2f9026e7.png">

2. Initiation:
<img width="479" alt="screen shot 2018-05-20 at 2 40 29 pm" src="https://user-images.githubusercontent.com/18134352/40283986-10de6420-5c3c-11e8-9c10-bfe322a40e72.png">

3. Post Method:
<img width="509" alt="screen shot 2018-05-20 at 2 40 44 pm" src="https://user-images.githubusercontent.com/18134352/40283988-19305638-5c3c-11e8-8338-a1b1025125f4.png">

But I'm getting error:
<img width="1427" alt="screen shot 2018-05-20 at 2 44 44 pm" src="https://user-images.githubusercontent.com/18134352/40284002-5bc8ff54-5c3c-11e8-908b-bb735bc52661.png">

Do I need to create another controller to handle this?

**Comment by Elfocrash** [comment]
You can just have both your `ICosmosStores` in the same contractor.
The .NET Core DI framework doesn't support multiple contractors.

You can also use the `[FromServices]` attribute to get the store in the specific method.

**Comment by kklan** [comment]
Is there anyway you can provide an example of syntax when you say both `ICosmosStores` in same contractor?

**Comment by Elfocrash** [comment]
Something like this
```csharp
    private readonly ICosmosStore<Car> _carStore;
    private readonly ICosmosStore<FriendStore> _friendStore;

    public HomeController(ICosmosStore<Car> carStore, ICosmosStore<FriendStore> friendStore)
    {
        _carStore = carStore;
        _friendStore = friendStore;
    }
```

**Comment by kklan** [comment]
Great thank you.

**Comment by kklan** [comment]
Opps close it too soon.

I made the change and it's still not liking that.

<img width="1376" alt="screen shot 2018-05-20 at 3 19 25 pm" src="https://user-images.githubusercontent.com/18134352/40284256-464eff3e-5c41-11e8-83c0-c0351242c62f.png">

**Comment by kklan** [comment]
I just had to add in `Startup.cs`
`
services.AddCosmosStore<Car>(settings);
services.AddCosmosStore<Friend>(settings);
`
