### ISSUE TITLE
Problems with partitionkey and FindAsync in a non-partitioned collection

### ISSUE THREAD

**Issue by gdahlin** [Elfocrash/Cosmonaut#28]
I use a shared collection (that is non-partitioned) for my implementation, and have added the `SharedCosmosCollection` attribute together with the `SharedCollectionName` property.

Persisting entities and query (all) works fine, but the `ICosmosStore.FindAsync` method generates the Exception:

> Microsoft.Azure.Documents.DocumentClientException: Partition key provided either doesn't correspond to definition in the collection or doesn't match partition key field values specified in the document.

Any help would be highly appreciated.

**Comment by Elfocrash** [comment]
Fixed in 2.3.2. You can update https://www.nuget.org/packages/Cosmonaut/2.3.2

PS: Give it a second to index the package

**Comment by gdahlin** [comment]
Works fine! Thanks for fast update!
