### ISSUE TITLE
throw DocumentClientException NotFound

### ISSUE THREAD

**Issue by fileman** [Elfocrash/Cosmonaut#46]
Hi, I've a test for NotFound resource by using wrong id.
DocumentClient throw this exception "Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["Resource Not Found"]}" in Visual Studio Locals tab $exception variable, but CosmonautClient return Success and no exception catched.
```
try
{
       result = await cosmosService.EntityStore.UpdateAsync(Entity.Value);
}
catch (DocumentClientException ex)
{
       var error = ex; //Breakpoint here ignored
       throw;
}

return result.Exception is null ? // this is null
     (ActionResult)new OkObjectResult($"Success") : 
     new BadRequestObjectResult($"Error");
```

**Comment by Elfocrash** [comment]
Cosmonaut does not throw for any document related exception and it does not return them either.

In the case of not found it should set the operation status to NotFound.

This is described in the readme and the docs: https://cosmonaut.readthedocs.io/en/latest/The-CosmosStore.html#cosmosresponse-and-response-handling

**Comment by fileman** [comment]
yes, I've readed it, but with wrong id in the UpdateAsync returned value CosmosOperationStatus is set to Success
![image](https://user-images.githubusercontent.com/17230763/50300720-8df02d80-0485-11e9-95f9-6af661becdd6.png)
I can't find why not found resource return success

**Comment by Elfocrash** [comment]
Oh ok I see. I will try to reproduce and get back to you. It should be a failure but not throw.
