### ISSUE TITLE
CosmosStore remove sealed from class and add virtual to methods

### ISSUE THREAD

**Issue by fileman** [Elfocrash/Cosmonaut#47]
hi, 
in my project I need to add some audit property (CreatedBy, CreatedAt, etc...), is possible to remove sealed from CosmosStore class and add virtual to its methods?
If you agree I can do a PR for these changes, otherwise I create a custom version in my project.
Thanks

**Comment by Elfocrash** [comment]
I won't be changing the seal and virtual tags but I'm wondering. What is the problem with adding those in a base class DTO and have your POCOs extend that class?

**Comment by fileman** [comment]
Those properties are in class, but I set their value in repository when entity is added, modified, soft-deleted o removed... maybe this isn't the better way to do it

**Comment by Elfocrash** [comment]
It sounds like you can still do it in the repository. CosmosDB also supports triggers so there's that too.

**Comment by fileman** [comment]
My bad design... I have replaced repository with cosmonaut, but is better if I use it inside the repository, thanks for the help
