### ISSUE TITLE
Call stored procedure

### ISSUE THREAD

**Issue by rhalaly** [Elfocrash/Cosmonaut#50]
First of all, I really like this project :).

How can we call a stored procedure with this library? I didn't see any interface in the docs or in `ComsosStorage`.

**Comment by Elfocrash** [comment]
Thanks for your kind words.

You can call a Stored Procedure by using the `CosmonautClient` class. This class is a client that can be initialised on it own but it is the client that the `CosmosStore` is using behind the scenes and you can access that by using `store.CosmonautClient`.

**Comment by rhalaly** [comment]
Thanks, I will try it!
