### ISSUE TITLE
Document count...

### ISSUE THREAD

**Issue by leonpotgieter** [Elfocrash/Cosmonaut#54]
Hi Nick,

Wondering if you perhaps support a way to count documents in a collection (multi-partition)?

Currently using SELECT VALUE COUNT(1) FROM C in the portal but it doesn't seem to work for collections with multiple partitions... or else it is taking forever to return a value as its been running for over 5m on approx 70k documents?

Thanks
Leon

**Comment by Elfocrash** [comment]
Hey Leon,

Did you try using the .CountAsync() method?
It returns the count of the documents in the collection cross partition.

**Comment by leonpotgieter** [comment]
Thanks Nick, will give that a go...

**Comment by Elfocrash** [comment]
Hey @leonpotgieter,

Is this one still an issue or can I close it?
