### ISSUE TITLE
Synthetic partition key

### ISSUE THREAD

**Issue by HMoen** [Elfocrash/Cosmonaut#69]
First, thank you for putting the work into this great library.

I see that you throw an exception if more than 1 property is decorated with the CosmosPartitionKey attribute. Is there a specific reason? 

Instead of having client code populate a single property with a synthetic partition key value (per MS [Create a synthetic partition key](https://docs.microsoft.com/en-us/azure/cosmos-db/synthetic-partition-keys)), could the CosmosPartitionKey be enhanced to allow multi-property decoration with an int position parameter to establish the assembly order? Then use PartitionKeyDefinition when creating the collection to include multiple paths.

**Comment by Elfocrash** [comment]
Hello @HMoen and thank you for your kind words.

The synthetic key is encouraged from me in general and I do personally use it in prod in multiple use cases.
The main problem with having multiple CosmosPartitionKey attributes would be that the library wouldn't know which one is the first part of the synthetic key and which one is the second.

The way I go about it is by creating an object like this:

```
class Example{
    public string Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [CosmosPartitionKey]
    public string PartitionKey => $"{FirstName}-{LastName}"
}
```
This ofc requires the property to be excluded on read it doesn't throw a no-setter exception.

The `PartitionKeyDefinition` does accept and array but this array is only allowed to have a single partition key path. When they say "synethic partition key" they don't mean, a `PartitionKeyDefinition` with 2 items in the array. They are talking about a single item which is the concatenated string of two other properties.

**Comment by HMoen** [comment]
Thanks for the clarification. I had wrongly assumed the [PKD](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.partitionkeydefinition?view=azure-dotnet) would take multiple paths since it is a string collection. In the portal, the placeholder text also shows /address/zipCode as a sample partition key (if I remember correctly) which made me think those were concatenated properties.

Your provided solution will do the trick. Is there a global setting to exclude the property on reads or will need to be set with every query?

Thanks again.

**Comment by Elfocrash** [comment]
You can specify your JSON conversion settings on both the request level or the CosmosStore level. It comes down to your usecase.

**Comment by HMoen** [comment]
Perfect, thanks.
