### ISSUE TITLE
Please close

### ISSUE THREAD

**Issue by allenzhang83** [Elfocrash/Cosmonaut#81]
With the current implementation, I believe there is no way to tell the web fontend client total number of pages without running a full collection scan.

This might be cosmos db limitation, but is there a way to do it?

And the ContinuationToken token approach is the recommended approach. But the user can't jump pages via this approach, right? For example, from page 1 to page 5.

Update: never mind, I spoke to the client, they're happy about the way Cosmonaut works now. Thanks for developing this wonderful library.

**Comment by shixiawg** [comment]
actually, don't worry about it. Close this issue, please. I spoke to the client, they're happy to work with the current mechanism of how Cosmonaut works. Thanks for developing this wonderful library.

**Comment by Elfocrash** [comment]
@allenzhang83 Thanks for your kind words. 

Keep in mind that one of the most requested features of CosmosDB is skip take pagination so whenever they finally implement it (if they do) I will change the `WithPagination` method to use whatever they choose to go with so you will benefit from the performance without any code changes.

**Comment by allenzhang83** [comment]
Thanks a lot!

**Comment by HMoen** [comment]
Finally! https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query#OffsetLimitClause

**Comment by allenzhang83** [comment]
This is great. Thanks a lot for sharing, will try it out.

**Comment by Elfocrash** [comment]
It's worth pointing out that you can't do cross partition pagination with those keywords. Only same partition ones.
