### ISSUE TITLE
PartitionKey exception during upsert

### ISSUE THREAD

**Issue by sivafirst** [Elfocrash/Cosmonaut#88]
When using CosmosPartitionKey attribute on integer type throws exception during upsert. But works fine when the type is string.   Not sure if it is an issue in cosmonaut!

Exception:
Microsoft.Azure.Documents.DocumentClientException : Message: {"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]}

**Comment by Elfocrash** [comment]
Your partition key cannot be an integer. CosmosDB only accepts string partition keys.
