### ISSUE TITLE
Xamarin.Forms supported

### ISSUE THREAD

**Issue by fileman** [Elfocrash/Cosmonaut#89]
I'm trying to use Cosmonaut in Xamarin.Forms, but something goes wrong when CosmosStore<T> is created,  without any exception... before I try to find and solve the problem, is there a known issue that prevent to use Cosmonaut with Xamarin.Forms?

**Comment by Elfocrash** [comment]
You should be able to use it in Xamarin forms without any problems. However Xamarin forms has a synchronization context. I would suggest you turn the `CosmosStoreSettings` option `ProvisionInfrastructureIfMissing` to false and try again. This means that you will have to create the database and the collection on your own.

**Comment by fileman** [comment]
this setting solved the problem, thanks.
Have you planned migration to Cosmos SDK V3?

**Comment by Elfocrash** [comment]
@fileman 

To answer the questions you deleted, I won't be migrating any time soon for the following reasons:
* v2 and v3 share the same core, so really v3 is just like Cosmonaut, a wrapper around v2
* The only performance improvement in v3 is the way exceptions are handled and even though it can be up to 30% faster, I don't see this being the reason I migrate
* v3 does a lot of things that Cosmonaut does anyway, and the Cosmos DB team used many similar patterns and in some cases the same names that Cosmonaut uses so I will also have to be very careful with what I use
* I first need v3 to be officially released and get adopted by people. I need to know it's stable and usable

**Comment by fileman** [comment]
Accidentally deleted, sorry.
thanks for reply.
