### ISSUE TITLE
Recommended practice for string id / guid id usage

### ISSUE THREAD

**Issue by DennisBaekgaard** [Elfocrash/Cosmonaut#93]
I tried searching around a little and couldn't find any information. I understand that CosmosDB enforces a string id property (for reasons unknown), but what is the recommended practice then? 
Was considering something like this: 

```
        [JsonProperty("id")]
        public string CosmosId { get; set; }
        public Guid Id { get { return Guid.Parse(CosmosId); } set { CosmosId = value.ToString(); Id = value; };
```

But that will get proper confusing with queries I'd suppose. I do kind a want the type security though.

**Comment by Elfocrash** [comment]
This will work indeed but you can simplify this to just:

Yeah if you need to have a Guid as the Id you deal with in the code then what you pasted will work.
The Id by default will be initialized as a string representation of a Guid anyway so if you don't set it will get initialized with Guid.NewGuid()

**Comment by DennisBaekgaard** [comment]
Awesome, thank you!
