### ISSUE TITLE
How can I measure the request units on a request?

### ISSUE THREAD

**Issue by crhistianramirez** [Elfocrash/Cosmonaut#98]
I'd like to see what the linq generated sql call is costing me. In the cosmos sdk there is a `RequestCharge` property you can inspect. Does cosmonaut offer something similar? 

If that's not an option is there a way to see the generated SQL so I can use the portal to determine the costs manually?

**Comment by Elfocrash** [comment]
When it comes to querying Cosmonaut is all about the entities, not the metadata. That part is abstracted out to the logging department. If you plug the CosmosEventStore to log it's telemetry in something like ApplicationInsights you will be able to get those numbers. They are however redacted from the `ToListAsync()` response.

More info on that can be found here: https://github.com/Elfocrash/Cosmonaut#logging

**Comment by crhistianramirez** [comment]
@Elfocrash  Thank you for the speedy reply!
